from flask import Flask, render_template, request, jsonify, send_from_directory
import os, requests, re, json
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# Environment variables
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/generated/<app_name>/<path:filename>")
def generated_files(app_name, filename):
    return send_from_directory(f"generated/{app_name}", filename)

@app.route("/chat", methods=["POST"])
def chat():
    prompt = request.json.get("prompt")
    if not prompt:
        return jsonify({"error": "No prompt provided"}), 400
    
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }
    
    # More detailed prompt to get better structured responses
    system_prompt = (
        "You are a PWA (Progressive Web App) code generator. "
        "Generate complete, ready-to-use code for a PWA based on the user's request. "
        "Provide only the raw code for three files: index.html, styles.css, and script.js. "
        "Separate each file with the following exact tags: "
        "[HTML]...[/HTML] "
        "[CSS]...[/CSS] "
        "[JS]...[/JS]"
    )
    
    data = {
        "model": "mistralai/mistral-7b-instruct",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Create a PWA for: {prompt}"}
        ]
    }

    try:
        response = requests.post(OPENROUTER_API_URL, headers=headers, json=data, timeout=30)
        response.raise_for_status()
        result = response.json()
        return jsonify({"response": result["choices"][0]["message"]["content"]})
    except requests.exceptions.Timeout:
        return jsonify({"error": "Request timeout"}), 408
    except requests.exceptions.RequestException as e:
        return jsonify({"error": f"API request failed: {str(e)}"}), 500
    except (KeyError, IndexError) as e:
        return jsonify({"error": f"Unexpected response format: {str(e)}"}), 500

def extract_code(response_text, file_type):
    """Extract code for a specific file type using multiple patterns"""
    patterns = [
        # Pattern 1: [HTML]...[/HTML]
        rf"\[{file_type}\](.*?)\[\/{file_type}\]",
        # Pattern 2: ```html...```
        rf"```(?:html|{file_type.lower()})\s*(.*?)```",
        # Pattern 3: <file_type> code: ... (fallback)
        rf"{file_type} code:(.*?)(?=\n\w+ code:|\Z)",
    ]
    
    for pattern in patterns:
        match = re.search(pattern, response_text, re.DOTALL | re.IGNORECASE)
        if match:
            return match.group(1).strip()
    
    return None

@app.route("/generate", methods=["POST"])
def generate_files():
    prompt = request.json.get("prompt")
    response_text = request.json.get("response_text")
    
    if not prompt or not response_text:
        return jsonify({"status": "error", "message": "Missing prompt or response text"}), 400
    
    # Create a safe directory name
    app_name = re.sub(r'[^a-z0-9\-]', '', prompt.replace(" ", "-").lower())
    app_dir = f"generated/{app_name}"
    os.makedirs(app_dir, exist_ok=True)

    # Extract code for each file type
    html_code = extract_code(response_text, "HTML")
    css_code = extract_code(response_text, "CSS")
    js_code = extract_code(response_text, "JS")
    
    files_created = []
    
    try:
        if html_code:
            with open(f"{app_dir}/index.html", "w", encoding="utf-8") as f:
                f.write(html_code)
            files_created.append("index.html")
        else:
            # Create a basic HTML template if extraction failed
            basic_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{prompt}</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="manifest" href="manifest.json">
</head>
<body>
    <h1>{prompt}</h1>
    <p>This is a PWA generated by the PWA Generator.</p>
    <script src="script.js"></script>
</body>
</html>"""
            with open(f"{app_dir}/index.html", "w", encoding="utf-8") as f:
                f.write(basic_html)
            files_created.append("index.html")
        
        if css_code:
            with open(f"{app_dir}/styles.css", "w", encoding="utf-8") as f:
                f.write(css_code)
            files_created.append("styles.css")
        else:
            # Create basic CSS if extraction failed
            basic_css = """body {
    font-family: Arial, sans-serif;
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    line-height: 1.6;
}"""
            with open(f"{app_dir}/styles.css", "w", encoding="utf-8") as f:
                f.write(basic_css)
            files_created.append("styles.css")
        
        if js_code:
            with open(f"{app_dir}/script.js", "w", encoding="utf-8") as f:
                f.write(js_code)
            files_created.append("script.js")
        else:
            # Create basic JS if extraction failed
            basic_js = "console.log('PWA loaded successfully');"
            with open(f"{app_dir}/script.js", "w", encoding="utf-8") as f:
                f.write(basic_js)
            files_created.append("script.js")
        
        # Generate a basic manifest for the PWA
        manifest_data = {
            "name": prompt,
            "short_name": app_name[:12],
            "start_url": "index.html",
            "display": "standalone",
            "background_color": "#ffffff",
            "theme_color": "#007BFF",
            "icons": [
                {
                    "src": "icon-192.png",
                    "sizes": "192x192",
                    "type": "image/png"
                },
                {
                    "src": "icon-512.png",
                    "sizes": "512x512",
                    "type": "image/png"
                }
            ]
        }
        
        with open(f"{app_dir}/manifest.json", "w", encoding="utf-8") as f:
            json.dump(manifest_data, f, indent=2)
        files_created.append("manifest.json")
        
        # Create a basic service worker
        sw_content = """self.addEventListener('install', e => {
  e.waitUntil(
    caches.open('pwa-store').then(cache => {
      return cache.addAll([
        './',
        './index.html',
        './styles.css',
        './script.js',
        './manifest.json'
      ]);
    })
  );
});

self.addEventListener('fetch', e => {
  e.respondWith(
    caches.match(e.request).then(response => {
      return response || fetch(e.request);
    })
  );
});
"""
        with open(f"{app_dir}/sw.js", "w", encoding="utf-8") as f:
            f.write(sw_content)
        files_created.append("sw.js")
        
        return jsonify({
            "status": "success", 
            "files": files_created, 
            "app_name": app_name,
            "preview_url": f"/generated/{app_name}/index.html"
        })
        
    except Exception as e:
        return jsonify({"status": "error", "message": f"File creation failed: {str(e)}"}), 500

if __name__ == "__main__":
    os.makedirs("generated", exist_ok=True)
    app.run(debug=True, port=5000)